name: Hello AI CI/CD

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ github.sha}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show Installed Packages
        run: |
          python --version
          pip --version
          pip list
          pip check

      - name: Verify Repository Structure
        run: |
          pwd
          ls -la
          find src -maxdepth 3 || true
          find tests -maxdepth 2 || true

      - name: Run Black
        run: |
          black --check src tests

      - name: Run Flake8
        run: |
          flake8 src tests

      - name: Run Pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest -v

      - name: Build Docker Image
        run: |
          docker build -t hello-ai:${{ github.sha }} .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name helloaiacr

      - name: Push Docker Image to Azure Container Registry
        run: |
          IMAGE_NAME=helloaiacr.azurecr.io/hello-ai:${{ github.sha }}

          echo "Tagging image as: $IMAGE_NAME"

          docker tag hello-ai:${{ github.sha }} $IMAGE_NAME

          echo "Pushing image to Azure Container Registry..."

          docker push $IMAGE_NAME
          
  deploy-experiment:
    name: Deploy to Experiment
    needs: ci
    runs-on: ubuntu-latest

    environment:
      name: experiment
    
    steps:
      - name: Deployment Summary
        run: |
          echo "=============================================="
          echo "Deployment Environment : experiment"
          echo "Repository             : ${{ github.repository }}"
          echo "Branch                 : ${{ github.ref_name }}"
          echo "Commit                 : ${{ github.sha }}"
          echo "Actor                  : ${{ github.actor }}"
          echo "Docker Image           : ghcr.io/${{ github.repository }}/hello-ai:${{ github.sha }}"
          echo "=============================================="}}

      - name: Simulate Deployment
        run: |
          echo "Deploying Docker image to Experiment. . . "
          sleep 5
          echo "Deployment to Experiment completed successfully!"

  deploy-uat:
    name: Deploy to UAT
    needs: deploy-experiment
    runs-on: ubuntu-latest

    environment:
      name: uat
    
    steps:
      - name: Deployment Summary
        run: |
          echo "=============================================="
          echo "Deployment Environment : uat"
          echo "Repository             : ${{ github.repository }}"
          echo "Branch                 : ${{ github.ref_name }}"
          echo "Commit                 : ${{ github.sha }}"
          echo "Actor                  : ${{ github.actor }}"
          echo "Docker Image           : ghcr.io/${{ github.repository }}:${{ github.sha }}"
          echo "=============================================="}}

      - name: Simulate UAT Deployment
        run: |
          echo "Deploying Docker image to UAT. . . "
          sleep 5
          echo "Deployment to UAT completed successfully!"

  deploy-production:
    name: Deploy to Production
    needs: deploy-uat
    runs-on: ubuntu-latest

    environment:
      name: production
    
    steps:
      - name: Deployment Summary
        run: |
          echo "=============================================="
          echo "Deployment Environment : production"
          echo "Repository             : ${{ github.repository }}"
          echo "Branch                 : ${{ github.ref_name }}"
          echo "Commit                 : ${{ github.sha }}"
          echo "Actor                  : ${{ github.actor }}"
          echo "Docker Image           : ghcr.io/${{ github.repository }}:${{ github.sha }}"
          echo "=============================================="}}

      - name: Simulate Production Deployment
        run: |
          echo "Deploying Docker image to Production. . . "
          sleep 5
          echo "Deployment to Production completed successfully!" 

  azure-login-test:
    name: Azure Login Test
    needs: deploy-production
    runs-on: ubuntu-latest

    steps:
      - name: Checkpoint Repository
        uses: actions/checkout@v4 

      - name: Login to Azure    
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure Account
        run: |
          az account show
          
      - name: List Azure Container Registries
        run: |
          az acr list --output table    